// <auto-generated />
using ACibao.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACibao.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220301185659_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ACibao.Entities.Itemdata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemnum")
                        .HasColumnType("int");

                    b.Property<int>("itemtypegroupnum")
                        .HasColumnType("int");

                    b.Property<int>("itemtypenum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("itemdata");
                });

            modelBuilder.Entity("ACibao.Entities.Itemdatapage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FILEPATH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("diskgroupnum")
                        .HasColumnType("int");

                    b.Property<int>("itemnum")
                        .HasColumnType("int");

                    b.Property<int>("logicalplatternum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("itemdatapage");
                });

            modelBuilder.Entity("ACibao.Entities.Physicalplatter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LASTUSEDDRIVE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("diskgroupnum")
                        .HasColumnType("int");

                    b.Property<int>("logicalplatternum")
                        .HasColumnType("int");

                    b.Property<int>("physicalplatternum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("physicalplatter");
                });

            modelBuilder.Entity("ACibao.Entities.Powerinfo", b =>
                {
                    b.Property<string>("PATH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemname")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PowerInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
